environment: production
# Replace my-github-org and open-sdg-data-starter as needed.
remote_data_prefix: "https://my-github-org.github.io/open-sdg-data-starter"

analytics:
  # For production, you likely want to enter a Google Analytics code below.
  ga_prod: ''
